FROM node:10.13-alpine
MAINTAINER kanagawa App Developer Ltd

RUN npm uninstall -g create-react-app
RUN npm install -g create-react-app

RUN mkdir /frontend
WORKDIR /frontend
COPY ./frontend/ /frontend
RUN npm install

