version: '2.4'

volumes:
  public:
    driver: local

services:
  app:
   build:
     context: .
   ports:
     - "8001"
   volumes:
     - public:/public
     - ./app:/app
   command: >
      sh -c "python manage.py migrate && uwsgi --ini /app/app/django.ini"
   environment:
    - DB_HOST=db
    - DB_NAME=app
    - DB_USER=postgres
    - DB_PASS=supersecretpassword
   container_name: app
   depends_on:
    db:
      condition: service_healthy

  db:
    image: postgres:10-alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
     - POSTGRES_DB=app
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=supersecretpassword
    container_name: db

  frontend:
      build:
        context: .
        dockerfile: "./Dockerfile-nodejs"
      volumes:
        - ./frontend:/frontend
      command: >
        sh -c "yarn start"
      ports:
        - "3000:3000"
      container_name: frontend
      depends_on:
        - app
      stdin_open: true

  nginx:
    image: nginx:1.15.9-alpine
    ports:
      - "80:80"
    volumes:
      - public:/public
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./nginx/log:/var/log/nginx
    container_name: nginx
    depends_on:
      - app
      - frontend

  redis:
    image: redis:3.0
    container_name: redis
